### ISSUE TITLE
Scrolling need to be smooth

### ISSUE THREAD

**Issue by RajeevDash007** [jarek-pacocha/jarek-pacocha.github.io#86]
while clicking the "Go to top" button, its scrolling rigidly, it has to be smooth.
assign me this issue so that I can solve it

**Comment by jarek-pacocha** [comment]
Hi @RajeevDash007,

I'm not experiencing this issue. It's not scrolling. Just jumps to the top of the page.

**Comment by RajeevDash007** [comment]
@jarek-pacocha ya exactly, it jumps to top directly, I want to make that process smooth, to makes its UI cool

**Comment by jarek-pacocha** [comment]
Thank you for pointing that out. I appreciate your interest. I actually prefer a fast jumo over a scroll. It's supposed to be a quick experience and I like it like that. But thanks anyway.
